### Generate Flashcard
POST http://127.0.0.1:8000/generate
Content-Type: application/json

{
  "word": "School",
  "user_language": "Spanish",
  "target_language": "English",
  "style": "realistic",
}
